name: Cargo Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable", "beta", "nightly"]
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@wasm-pack
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm trunk
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build
      - run: wasm-pack test --firefox --headless
      - run: (cd examples/counter && trunk build)
      - run: (cd examples/svg && trunk build)
